#
# NOTICE (shared library): This file is SYNCHRONIZED from pipelines/.shared directory
#

#
# NOTICE: This file is synchronized on-demand by synchronize.yaml job from a shared library directory
#

name: Synchronize pipelines
on:
    workflow_dispatch:

jobs:
    generate-changelog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.WORKFLOW_UPDATE_TOKEN }}

            - name: Synchronize files
              run: |
                  sh ci-sync.sh

            - name: Commit and push
              run: |
                  git config --global user.email "github@example.org"
                  git config --global user.name "GitHub Actions"
                  
                  git add .github
                  git commit -m "chore: synchronize pipelines [skip ci]" || true
                  git push --force
