# ============================================
#  Propagates files from
#    - pipelines/.shared/* to pipelines/*/*
#    - packs/.shared/* to packs/*/*
# ============================================

name: Propagate shared structure
on:
    push:
        branches:
            - 'main'

jobs:
    propagate:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Copy files
              run: |
                  bash .github/helpers/propagate.sh starters
                  bash .github/helpers/propagate.sh pipelines

            - name: Commit and push
              run: |
                  git config --global user.email "github@example.org"
                  git config --global user.name "GitHub Actions"
                  
                  git add starters pipelines
                  git commit -m "chore: propagate files [skip ci]" || true
                  git checkout -b release || true
                  git checkout release
                  git push --force
