# ============================================
#  Propagates files from
#    - pipelines/.shared/* to pipelines/*/*
#    - packs/.shared/* to packs/*/*
# ============================================

name: Propagate shared structure
on:
    schedule:
        - cron: "15 17 * * *"
    workflow_dispatch:

jobs:
    propagate:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Copy files
              run: |
                  bash .github/helpers/propagate.sh starters
                  bash .github/helpers/propagate.sh pipelines

            - name: Commit and push
              run: |
                  git add .github
                  git commit -m "chore: propagate files" || true
                  git push --force
